# Generated by Django 4.2.6 on 2023-10-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=255)),
                ('send_time', models.TimeField(verbose_name='Send time')),
                ('frequency', models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='daily', max_length=10)),
                ('status', models.CharField(choices=[('1', 'закончить'), ('2', 'сохранить'), ('3', 'запустить')], default='3', verbose_name='Status')),
                ('client', models.ManyToManyField(to='rassilki.client', verbose_name='Clients')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Time')),
                ('log_status', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=50, null=True, verbose_name='Status')),
                ('log_server_response', models.TextField(blank=True, null=True, verbose_name='Server response')),
                ('log_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rassilki.client', verbose_name='Client')),
                ('log_mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rassilki.mailingmessage', verbose_name='Mailing')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
